spring:
  application:
    name: prueba_tecnica_accenture
  data:
    mongodb:
      uri: mongodb://localhost:27017/franquicias

logging:
  level:
    '[org.springframework.web]': DEBUG

server:
  port: 8080